import { WEBSITE_NAME } from "@/lib/config/constant";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: `%s | ${WEBSITE_NAME}`,
    default: `${WEBSITE_NAME}`,
  },
  description: "Generated by create next app",
};

// export const metadata: Metadata = {
//   title: WEBSITE_NAME,
//   description: `${WEBSITE_NAME} `,
//   metadataBase: new URL("https://it-udvc-pms.vercel.app/"),
//   twitter: {
//     card: "summary_large_image",
//     site: "it-udvc-pms.vercel.app",
//     title: WEBSITE_NAME,
//     description: `${WEBSITE_NAME} `,
//     images: ["https://it-udvc-pms.vercel.app/picture1.jpg"],
//   },
//   openGraph: {
//     title: WEBSITE_NAME,
//     description: `${WEBSITE_NAME} `,
//     images: ["https://it-udvc-pms.vercel.app/picture1.jpg"],
//   },
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="flex-1 overflow-y-auto ">{children}</main>;
}
