/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { WEBSITE_NAME } from "@/lib/config";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import { geistMono, geistSans } from "@/font/font";

export const metadata: Metadata = {
  title: {
    template: `%s | ${WEBSITE_NAME}`,
    default: `${WEBSITE_NAME}`,
  },
  description: "Generated by create next app",
};
// export const metadata: Metadata = {
//   title: WEBSITE_NAME,
//   description: `${WEBSITE_NAME} `,
//   metadataBase: new URL("https://it-udvc-pms.vercel.app/"),
//   twitter: {
//     card: "summary_large_image",
//     site: "it-udvc-pms.vercel.app",
//     title: WEBSITE_NAME,
//     description: `${WEBSITE_NAME} `,
//     images: ["https://it-udvc-pms.vercel.app/picture1.jpg"],
//   },
//   openGraph: {
//     title: WEBSITE_NAME,
//     description: `${WEBSITE_NAME} `,
//     images: ["https://it-udvc-pms.vercel.app/picture1.jpg"],
//   },
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
